create database eDNA_db_1;
USE eDNA_db_1;

CREATE TABLE eDNA_Data (
  `S.No.` INT NOT NULL AUTO_INCREMENT,
  `common_name` VARCHAR(255) NOT NULL,
  `scientific_name` VARCHAR(255) NOT NULL,
  `Location` varchar(255) Not Null,
  `CO1_marker` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`S.No.`)
);
SHOW TABLES;
SELECT * FROM eDNA_Data;
INSERT INTO eDNA_Data (common_name, scientific_name,Location, CO1_marker) VALUES ('Spinner shark', 'Carcharhinus brevipinna', 'West Bengal',  'CCTTTACCTGATTTTTGGTGCATGAGCAGGTATAGTTGGAACAGCCCTAAGTCTCCTTATTCGAGCTGAACTTGGGCAACCTGGATCACTTTTAGGGGATGATCAGATCTACAATGTAATCGTAACCGCCCACGCTTTTGTAATAATCTTTTTCATGGTTATACCAATTATAATTGGTGGTTTCGGAAACTGACTAGTTCCCTTAATAATTGGTGCACCAGATATAGCCTTCCCACGGATAAATAACATAAGCTTCTGACTCCTTCCACCATCATTTCTTCTTCTCCTCGCCTCTGCTGGAGTAGAAGCTGGAGCAGGTACTGGTTGAACAGTTTATCCTCCATTAGCTAGCAACCTAGCACATGCTGGACCATCTGTTGATTTAGCTATTTTCTCTCTTCACTTAGCCGGTGTTTCATCAATCTTAGCTTCAATTAATTTTATCACAACTATTATTAACATAAAACCACCAGCCATTTCCCAATATCAAACACCATTATTTGTTTGATCTATTCTTGTAACCACTATTCTTCTTCTCCTTTCACTTCCAGTCCTTGCAGCAGGGATTACAATATTACTTACAGATCGTAACCTTAATACTACATTCTTTGACCCTGCAGGCGGAGGAGACCCAATCCTTTATCAACATTTA
');
 INSERT INTO eDNA_Data (common_name, scientific_name, CO1_marker) VALUES ('Salmon', 'Oncorhynchus nerka', 'ATGGCTTGAACTCAGATCATG');
drop table edna_Data;
ALTER TABLE eDNA_Data
MODIFY CO1_marker VARCHAR(5000);
